# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: posts.proto for package 'asnp'

require 'grpc'
require 'posts_pb'

module Asnp
  module Posts
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'asnp.Posts'

      rpc :List, PostsListRequest, PostsListResponse
      rpc :Get, PostGetRequest, Post
    end

    Stub = Service.rpc_stub_class
  end
end
